### PR TITLE
#53 Add github actions to build osx distribution

### PR DESCRIPTION
**Pull request by sangohan**
This PR is for issue https://github.com/deepnight/led/issues/53 

I found out that github actions allow the use of mac osx build machines. This should be used to build the mac (and windows and linux in the future!) distributions! Saves having to own a mac.

The main.yml is fairly pedestrian and only builds on the mac, but github actions has the ability to run a matrix of builds, so in the future, it's easy to just add the windows and linux targets and get all distros built in one go.

Edit: see this sample build on my clone for a downloadable distribution: https://github.com/sangohan/led/actions/runs/276443783

### CODE REVIEW

**Comment by jminor** [comment]
@sangohan do these build archives actually work for you? I found that I had to do a bunch of fixing of permissions and symlinks to make them run. Specifically this:

```
#!/bin/sh

# first cd into LED.app/Contents
# then run this script

chmod +x MacOS/LEd

chmod +x Frameworks/*.app/Contents/MacOS/*

for i in Electron\ Framework Squirrel Mantle ReactiveCocoa
do

	rm "Frameworks/$i.framework/Versions/Current"
	ln -s A "Frameworks/$i.framework/Versions/Current"

	rm "Frameworks/$i.framework/$i"
	ln -s "Versions/Current/$i" "Frameworks/$i.framework/$i"

	rm "Frameworks/$i.framework/Helpers"
	ln -s "Versions/Current/Helpers" "Frameworks/$i.framework/Helpers"

	rm "Frameworks/$i.framework/Libraries"
	ln -s "Versions/Current/Libraries" "Frameworks/$i.framework/Libraries"

	rm "Frameworks/$i.framework/Resources"
	ln -s "Versions/Current/Resources" "Frameworks/$i.framework/Resources"

	chmod +x "Frameworks/$i.framework/$i"

done
```

**Comment by sangohan** [comment]
I downloaded it and it seems to work. What version of mac are you using? i'm using 10.14.6 (18G6032) Mojave , which is not the latest. But electron shouldn't require it. 

Also, when you unzip, how are you doing it? I think your unzip app may be screwing with the files, or not respecting the zip's stored exec bits.

**Comment by jminor** [comment]
I tested on 4 combinations of 10.14 and 10.15, using Finder and /usr/bin/unzip. Only one of those four works. Here are the results:

macOS 10.14.6:
- Double-click `mac-distribution.zip` in Finder.
- Archive Utility runs.
- `LEd 0.4.0-beta installer.zip` appears & disappears
- `LEd.app` appears.
- Double-click `LEd.app` and the app runs fine.

macOS 10.14.6:
- Run `/usr/bin/unzip mac-distribution.zip` from Terminal.
- `LEd 0.4.0-beta installer.zip` extracted.
- Run `/usr/bin/unzip "LEd 0.4.0-beta installer.zip"`
- Fails with this message:
```
Archive:  LEd 0.4.0-beta installer.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of LEd 0.4.0-beta installer.zip or
        LEd 0.4.0-beta installer.zip.zip, and cannot find LEd 0.4.0-beta installer.zip.ZIP, period.
```

macOS 10.15.6:
- Double-click `mac-distribution.zip` in Finder.
- Archive Utility runs.
- `LEd 0.4.0-beta installer.zip` appears & disappears
- `LEd.app` appears.
- Double-click `LEd.app` and the app fails to launch.
- Finder complains: `The application "LEd.app" can't be opened.`
- Looking inside, I see nothing has executable bit, and the symlinks are text files instead.

macOS 10.15.6:
- Run `/usr/bin/unzip mac-distribution.zip` from Terminal.
- `LEd 0.4.0-beta installer.zip` extracted.
- Run `/usr/bin/unzip "LEd 0.4.0-beta installer.zip"`
- Fails with this message:
```
Archive:  LEd 0.4.0-beta installer.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of LEd 0.4.0-beta installer.zip or
        LEd 0.4.0-beta installer.zip.zip, and cannot find LEd 0.4.0-beta installer.zip.ZIP, period.
```

**Comment by sangohan** [comment]
It's as i suspected - the zip probably is broken when extracted using different unzip utilities. 

I'm gonna change to use the DMG file instead of the zip. That should work.

**Comment by jminor** [comment]
That worked great! I was able to download the new build on both 10.14 and 10.15 and both worked.

macOS 14, or 10.15:
- Double click `mac-distribution.zip`
- Archive Utility runs
- `LEd 0.4.0-beta installer.dmg` appears
- Double-click the dmg.
- A window opens with LEd.app and an arrow asking you to drag to Applications.
- Drag to Applications.
macOS 10.14:
- Double-click LEd.app in Applications.
- It runs!
macOS 10.15:
- Right-click and choose "Open" and then answer the prompt about un-signed applications.
- It runs!

Thanks so much for the fix!

**Pull request merged**
